name: test

on:
  pull_request:
    # ignore PR nervosnetwork/ckb#2019
    branches-ignore: [ master ]
  push:
    branches: [ master, staging, staging2, trying ]

env:
  ci_rust_version: 1.41.0

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ env.ci_rust_version }}
            override: true

      - name: Install Windows Dependencies
        if: startsWith(matrix.os, 'windows')
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install llvm
          scoop install msys2
          scoop install yasm
          echo "::set-output name=clang_version::$(clang --version)"
          echo "::set-output name=yasm_version::$(yasm --version)"
          echo "::add-path::${env:USERPROFILE}\scoop\shims"
        shell: powershell

      - name: Run Test
        run: make test
